services:
  db:
    container_name: db
    image: postgres:13.2
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    ports:
      - "9090:5432"
